import Head from "next/head";
import '../styles/index.css'
import "../styles/map.css"
import "../styles/label.css"

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Visualize data</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp
